services:
  - type: web
    name: maloka-store
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./database/store.db
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
